spring:
  application:
    name: transfer
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true

id:
  snowflake:
    node-id: ${SNOWFLAKE_NODE_ID:1}
    custom-epoch: 1704067200000       # 2024-01-01 00:00:00Z
    max-clock-backward-ms: 5