version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: fds-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: fds
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
