spring:
  application.name: fds-api-server
  datasource:
    url: jdbc:postgresql://localhost:5432/fds
    username: postgres
    password: pass1234
  jpa:
    hibernate:
      ddl-auto: create # TODO : 개발 환경에서는 update, 운영 환경에서는 none 으로 설정한다.
    show-sql: true